### Publish cards to json
POST http://192.168.33.10:3000/api/publish_cards.json

### Generated cards
GET http://192.168.33.10:3000/g/cards.json

### fetch card data
POST http://192.168.33.10:3000/api/fetch_card_data.json
Content-Type: application/json

{"product_no": "WXD-12", "product_type": "starter"}


### force update card
POST http://192.168.33.10:3000/api/force_update_db.json
Content-Type: application/json

{"product_no": "WXDi-CP01"}

### append data extend parameter setting
POST http://192.168.33.10:3000/api//create_extend_parameter_setting.json
Content-Type: application/json

{"slug": "WX22-Re12", "json": "{\"img\": \"WD12/WD12-007.jpg\"}", "method": "extend"}