### Publish cards to json
POST http://192.168.33.10:3000/api/publish_cards.json

### Generated cards
GET http://192.168.33.10:3000/g/cards.json

### fetch card data
POST http://192.168.33.10:3000/api/fetch_card_data.json
Content-Type: application/json

{"product_no": "WXi-CP01", "product_type": "booster"}


### force update card
POST http://192.168.33.10:3000/api/force_update_db.json
Content-Type: application/json

{"product_no": "WXi-09"}

### append data extend parameter setting
POST http://192.168.33.10:3000/api/create_extend_parameter_setting.json
Content-Type: application/json

{"slug": "WX22-Re12", "json": "{\"img\": \"WD12/WD12-007.jpg\"}", "method": "extend"}


### login success
POST http://192.168.33.10:3000/api/auth/login
Content-Type: application/json

{
  "login_id": "taro",
  "password": "password"
}


### login failure
POST http://192.168.33.10:3000/api/auth/login
Content-Type: application/json

{
  "login_id": "taro",
  "password": "wrong password"
}

### who are you
GET http://192.168.33.10:3000/api/auth/


### create user
POST http://192.168.33.10:3000/api/auth/create_user
Content-Type: application/json

{
  "name": "管理者ユーザーTaro",
  "login_id": "taro",
  "password": "password"
}


### card detail
GET http://192.168.33.10:3000/api/admin/card_detail/WXDi-P00-036



### save deck
POST http://192.168.33.10:3000/api/save_deck
Content-Type: application/json

{"a":  100}
